# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_carpeta = QtWidgets.QPushButton(self.centralwidget)
        self.b_carpeta.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.b_carpeta.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.b_carpeta.setObjectName("b_carpeta")
        self.carpeta = QtWidgets.QLabel(self.centralwidget)
        self.carpeta.setGeometry(QtCore.QRect(160, 10, 531, 31))
        self.carpeta.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"DFGothic-EB\";")
        self.carpeta.setAlignment(QtCore.Qt.AlignCenter)
        self.carpeta.setObjectName("carpeta")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 310, 771, 231))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 180, 111, 16))
        self.label.setObjectName("label")
        self.principio = QtWidgets.QLineEdit(self.centralwidget)
        self.principio.setGeometry(QtCore.QRect(130, 180, 651, 20))
        self.principio.setObjectName("principio")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 160, 181, 16))
        self.label_4.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: italic 8pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 210, 211, 16))
        self.label_6.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: italic 8pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.fin = QtWidgets.QLineEdit(self.centralwidget)
        self.fin.setGeometry(QtCore.QRect(130, 230, 651, 20))
        self.fin.setObjectName("fin")
        self.fondo_1 = QtWidgets.QLabel(self.centralwidget)
        self.fondo_1.setGeometry(QtCore.QRect(0, 0, 811, 51))
        self.fondo_1.setStyleSheet("background-color: rgb(127, 140, 141);")
        self.fondo_1.setText("")
        self.fondo_1.setObjectName("fondo_1")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 150, 801, 111))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.t_salida = QtWidgets.QTextEdit(self.centralwidget)
        self.t_salida.setEnabled(True)
        self.t_salida.setGeometry(QtCore.QRect(10, 310, 771, 231))
        self.t_salida.setStyleSheet("font: 8pt \"VAGRounded BT\";\n"
"padding: 5px;")
        self.t_salida.setReadOnly(True)
        self.t_salida.setObjectName("t_salida")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 50, 801, 91))
        self.label_7.setStyleSheet("background-color: rgb(189, 195, 199);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-4, 50, 801, 31))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Impact\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.check_convertir = QtWidgets.QCheckBox(self.centralwidget)
        self.check_convertir.setGeometry(QtCore.QRect(10, 90, 171, 17))
        self.check_convertir.setStyleSheet("color: rgb(85, 85, 0);")
        self.check_convertir.setChecked(True)
        self.check_convertir.setObjectName("check_convertir")
        self.check_reparar = QtWidgets.QCheckBox(self.centralwidget)
        self.check_reparar.setEnabled(True)
        self.check_reparar.setGeometry(QtCore.QRect(10, 110, 151, 17))
        self.check_reparar.setStyleSheet("color: rgb(85, 85, 0);")
        self.check_reparar.setChecked(True)
        self.check_reparar.setObjectName("check_reparar")
        self.check_pdf = QtWidgets.QCheckBox(self.centralwidget)
        self.check_pdf.setEnabled(True)
        self.check_pdf.setGeometry(QtCore.QRect(260, 90, 201, 17))
        self.check_pdf.setStyleSheet("color: rgb(85, 85, 0);")
        self.check_pdf.setChecked(True)
        self.check_pdf.setObjectName("check_pdf")
        self.quitar = QtWidgets.QLineEdit(self.centralwidget)
        self.quitar.setEnabled(False)
        self.quitar.setGeometry(QtCore.QRect(70, 280, 133, 20))
        self.quitar.setObjectName("quitar")
        self.b_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.b_iniciar.setGeometry(QtCore.QRect(639, 269, 141, 31))
        self.b_iniciar.setObjectName("b_iniciar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(20, 280, 34, 16))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"display: invisible;")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(676, 20, 71, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"DFGothic-EB\";")
        self.label_2.setObjectName("label_2")
        self.seleccionados = QtWidgets.QLabel(self.centralwidget)
        self.seleccionados.setGeometry(QtCore.QRect(746, 20, 20, 21))
        self.seleccionados.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"DFGothic-EB\";")
        self.seleccionados.setObjectName("seleccionados")
        self.progreso = QtWidgets.QProgressBar(self.centralwidget)
        self.progreso.setGeometry(QtCore.QRect(10, 550, 771, 31))
        self.progreso.setProperty("value", 0)
        self.progreso.setTextVisible(False)
        self.progreso.setObjectName("progreso")
        self.quitar.raise_()
        self.b_iniciar.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.fondo_1.raise_()
        self.b_carpeta.raise_()
        self.carpeta.raise_()
        self.scrollArea.raise_()
        self.label.raise_()
        self.principio.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.fin.raise_()
        self.label_2.raise_()
        self.seleccionados.raise_()
        self.t_salida.raise_()
        self.label_9.raise_()
        self.check_convertir.raise_()
        self.check_reparar.raise_()
        self.check_pdf.raise_()
        self.progreso.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_carpeta.setText(_translate("MainWindow", "Seleccionar Carpeta"))
        self.carpeta.setText(_translate("MainWindow", "...."))
        self.label.setText(_translate("MainWindow", "Desde principio hasta:"))
        self.principio.setText(_translate("MainWindow", "</div><!-- .header-wrapper -->"))
        self.label_4.setText(_translate("MainWindow", "Todo hasta este texto sera borrado"))
        self.label_5.setText(_translate("MainWindow", "Despues desde:"))
        self.label_6.setText(_translate("MainWindow", "Todo despues de este texto sera borrado"))
        self.fin.setText(_translate("MainWindow", "</article><!-- #post-## -->"))
        self.label_9.setText(_translate("MainWindow", "Miscelaneas"))
        self.check_convertir.setText(_translate("MainWindow", "Convertir codificacion a ANSI"))
        self.check_reparar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Se cambiaran los nombres de archivos por los capitulos y se borraran caracteres basura de la cabecera</p></body></html>"))
        self.check_reparar.setText(_translate("MainWindow", "Tratar de reparar titulos"))
        self.check_pdf.setText(_translate("MainWindow", "Exportar a pdf en archivos separados"))
        self.b_iniciar.setText(_translate("MainWindow", "Iniciar Procesamiento"))
        self.label_3.setText(_translate("MainWindow", "Quitar:"))
        self.label_2.setText(_translate("MainWindow", "Archivos: "))
        self.seleccionados.setText(_translate("MainWindow", "...."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

